---
title: "hw8_yw3204"
author: "wyh"
date: "11/27/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.
```{r}
n <- 100
p <- 10
s <- 3
set.seed(0)
x <- matrix(rnorm(n*p), n, p)
b <- c(-0.7, 0.7, 1, rep(0, p-s))
y <- x %*% b + rt(n, df=2)

cor(x, y)
```
It is not possible to pick out each of the 3 relevant variables based on correlations alone. Theoreticcaly, the three relevant variables should be the first three. But based on the correlation, the three chosen are apparently not the first three.

## 2.
```{r}
range <- seq(-4, 4, 0.01)
plot(range, dnorm(range), type = "l", ylab = "density")
lines(range, dt(range, 3), col = "blue")
legend(-4, 0.4, legend=c("standard normal", "t-distribution with df=3"), col=c("black", "blue"), pch=c(16, 16), cex = 0.8)
```

## 3.
```{r}
psi <- function(r, c = 1) {
  return(ifelse(r^2 > c^2, 2*c*abs(r) - c^2, r^2))
}

huber.loss <- function(beta) {
  resd <- x %*% beta - y
  res <- sum(psi(resd))
  return(res)
}
```

## 4.
```{r}
grad.descent <- function() {
  
}
```







